<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RoomCrowdDatetimeStatus', 'doctrine');

/**
 * BaseRoomCrowdDatetimeStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $rcds_cd_key
 * @property string $rcds_nm_name
 * @property Doctrine_Collection $RoomCrowdDatetime
 * 
 * @method integer                 getRcdsCdKey()         Returns the current record's "rcds_cd_key" value
 * @method string                  getRcdsNmName()        Returns the current record's "rcds_nm_name" value
 * @method Doctrine_Collection     getRoomCrowdDatetime() Returns the current record's "RoomCrowdDatetime" collection
 * @method RoomCrowdDatetimeStatus setRcdsCdKey()         Sets the current record's "rcds_cd_key" value
 * @method RoomCrowdDatetimeStatus setRcdsNmName()        Sets the current record's "rcds_nm_name" value
 * @method RoomCrowdDatetimeStatus setRoomCrowdDatetime() Sets the current record's "RoomCrowdDatetime" collection
 * 
 * @package    RoomManager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoomCrowdDatetimeStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('room_crowd_datetime_status');
        $this->hasColumn('rcds_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('rcds_nm_name', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 40,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('RoomCrowdDatetime', array(
             'local' => 'rcds_cd_key',
             'foreign' => 'rcds_cd_key'));
    }
}