<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Teacher', 'doctrine');

/**
 * BaseTeacher
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $teac_cd_key
 * @property string $teac_nm_name
 * @property string $teac_nm_email
 * @property Doctrine_Collection $Crowd
 * 
 * @method integer             getTeacCdKey()     Returns the current record's "teac_cd_key" value
 * @method string              getTeacNmName()    Returns the current record's "teac_nm_name" value
 * @method string              getTeacNmEmail()   Returns the current record's "teac_nm_email" value
 * @method Doctrine_Collection getCrowd()         Returns the current record's "Crowd" collection
 * @method Teacher             setTeacCdKey()     Sets the current record's "teac_cd_key" value
 * @method Teacher             setTeacNmName()    Sets the current record's "teac_nm_name" value
 * @method Teacher             setTeacNmEmail()   Sets the current record's "teac_nm_email" value
 * @method Teacher             setCrowd()         Sets the current record's "Crowd" collection
 * 
 * @package    RoomManager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeacher extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('teacher');
        $this->hasColumn('teac_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('teac_nm_name', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
        $this->hasColumn('teac_nm_email', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 80,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Crowd', array(
             'local' => 'teac_cd_key',
             'foreign' => 'teac_cd_key'));
    }
}