<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Crowd', 'doctrine');

/**
 * BaseCrowd
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $crow_cd_key
 * @property integer $teac_cd_key
 * @property string $crow_nm_name
 * @property integer $crow_nb_module
 * @property integer $subj_cd_key
 * @property Subject $Subject
 * @property Teacher $Teacher
 * @property Doctrine_Collection $RoomCrowdDatetime
 * 
 * @method integer             getCrowCdKey()         Returns the current record's "crow_cd_key" value
 * @method integer             getTeacCdKey()         Returns the current record's "teac_cd_key" value
 * @method string              getCrowNmName()        Returns the current record's "crow_nm_name" value
 * @method integer             getCrowNbModule()      Returns the current record's "crow_nb_module" value
 * @method integer             getSubjCdKey()         Returns the current record's "subj_cd_key" value
 * @method Subject             getSubject()           Returns the current record's "Subject" value
 * @method Teacher             getTeacher()           Returns the current record's "Teacher" value
 * @method Doctrine_Collection getRoomCrowdDatetime() Returns the current record's "RoomCrowdDatetime" collection
 * @method Crowd               setCrowCdKey()         Sets the current record's "crow_cd_key" value
 * @method Crowd               setTeacCdKey()         Sets the current record's "teac_cd_key" value
 * @method Crowd               setCrowNmName()        Sets the current record's "crow_nm_name" value
 * @method Crowd               setCrowNbModule()      Sets the current record's "crow_nb_module" value
 * @method Crowd               setSubjCdKey()         Sets the current record's "subj_cd_key" value
 * @method Crowd               setSubject()           Sets the current record's "Subject" value
 * @method Crowd               setTeacher()           Sets the current record's "Teacher" value
 * @method Crowd               setRoomCrowdDatetime() Sets the current record's "RoomCrowdDatetime" collection
 * 
 * @package    RoomManager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCrowd extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('crowd');
        $this->hasColumn('crow_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('teac_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('crow_nm_name', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('crow_nb_module', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('subj_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Subject', array(
             'local' => 'subj_cd_key',
             'foreign' => 'subj_cd_key'));

        $this->hasOne('Teacher', array(
             'local' => 'teac_cd_key',
             'foreign' => 'teac_cd_key'));

        $this->hasMany('RoomCrowdDatetime', array(
             'local' => 'crow_cd_key',
             'foreign' => 'crow_cd_key'));
    }
}