<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CrowdRoomStatus', 'doctrine');

/**
 * BaseCrowdRoomStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $crrs_cd_key
 * @property string $crrs_nm_name
 * @property Doctrine_Collection $CrowdRoom
 * 
 * @method integer             getCrrsCdKey()    Returns the current record's "crrs_cd_key" value
 * @method string              getCrrsNmName()   Returns the current record's "crrs_nm_name" value
 * @method Doctrine_Collection getCrowdRoom()    Returns the current record's "CrowdRoom" collection
 * @method CrowdRoomStatus     setCrrsCdKey()    Sets the current record's "crrs_cd_key" value
 * @method CrowdRoomStatus     setCrrsNmName()   Sets the current record's "crrs_nm_name" value
 * @method CrowdRoomStatus     setCrowdRoom()    Sets the current record's "CrowdRoom" collection
 * 
 * @package    RoomManager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCrowdRoomStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('crowd_room_status');
        $this->hasColumn('crrs_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('crrs_nm_name', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 40,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CrowdRoom', array(
             'local' => 'crrs_cd_key',
             'foreign' => 'crrs_cd_key'));
    }
}