<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Building', 'doctrine');

/**
 * BaseBuilding
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $buil_cd_key
 * @property string $buil_nm_name
 * @property Doctrine_Collection $Room
 * @property Doctrine_Collection $Room_2
 * 
 * @method integer             getBuilCdKey()    Returns the current record's "buil_cd_key" value
 * @method string              getBuilNmName()   Returns the current record's "buil_nm_name" value
 * @method Doctrine_Collection getRoom()         Returns the current record's "Room" collection
 * @method Doctrine_Collection getRoom2()        Returns the current record's "Room_2" collection
 * @method Building            setBuilCdKey()    Sets the current record's "buil_cd_key" value
 * @method Building            setBuilNmName()   Sets the current record's "buil_nm_name" value
 * @method Building            setRoom()         Sets the current record's "Room" collection
 * @method Building            setRoom2()        Sets the current record's "Room_2" collection
 * 
 * @package    RoomManager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBuilding extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('building');
        $this->hasColumn('buil_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('buil_nm_name', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 40,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Room', array(
             'local' => 'buil_cd_key',
             'foreign' => 'buil_cd_key'));

        $this->hasMany('Room as Room_2', array(
             'local' => 'buil_cd_key',
             'foreign' => 'buil_cd_key'));
    }
}