<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CourseSubjectCrowd', 'doctrine');

/**
 * BaseCourseSubjectCrowd
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cosc_cd_key
 * @property integer $cour_cd_key
 * @property integer $subj_cd_key
 * @property integer $crow_cd_key
 * @property integer $cosc_nb_slot
 * @property Crowd $Crowd
 * @property Course $Course
 * @property Subject $Subject
 * 
 * @method integer            getCoscCdKey()    Returns the current record's "cosc_cd_key" value
 * @method integer            getCourCdKey()    Returns the current record's "cour_cd_key" value
 * @method integer            getSubjCdKey()    Returns the current record's "subj_cd_key" value
 * @method integer            getCrowCdKey()    Returns the current record's "crow_cd_key" value
 * @method integer            getCoscNbSlot()   Returns the current record's "cosc_nb_slot" value
 * @method Crowd              getCrowd()        Returns the current record's "Crowd" value
 * @method Course             getCourse()       Returns the current record's "Course" value
 * @method Subject            getSubject()      Returns the current record's "Subject" value
 * @method CourseSubjectCrowd setCoscCdKey()    Sets the current record's "cosc_cd_key" value
 * @method CourseSubjectCrowd setCourCdKey()    Sets the current record's "cour_cd_key" value
 * @method CourseSubjectCrowd setSubjCdKey()    Sets the current record's "subj_cd_key" value
 * @method CourseSubjectCrowd setCrowCdKey()    Sets the current record's "crow_cd_key" value
 * @method CourseSubjectCrowd setCoscNbSlot()   Sets the current record's "cosc_nb_slot" value
 * @method CourseSubjectCrowd setCrowd()        Sets the current record's "Crowd" value
 * @method CourseSubjectCrowd setCourse()       Sets the current record's "Course" value
 * @method CourseSubjectCrowd setSubject()      Sets the current record's "Subject" value
 * 
 * @package    RoomManager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCourseSubjectCrowd extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('course_subject_crowd');
        $this->hasColumn('cosc_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cour_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('subj_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('crow_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cosc_nb_slot', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Crowd', array(
             'local' => 'crow_cd_key',
             'foreign' => 'crow_cd_key'));

        $this->hasOne('Course', array(
             'local' => 'cour_cd_key',
             'foreign' => 'cour_cd_key'));

        $this->hasOne('Subject', array(
             'local' => 'subj_cd_key',
             'foreign' => 'subj_cd_key'));
    }
}