<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CrowdRoom', 'doctrine');

/**
 * BaseCrowdRoom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $crro_cd_key
 * @property integer $crow_cd_key
 * @property integer $room_cd_key
 * @property integer $crrs_cd_key
 * @property CrowdRoomStatus $CrowdRoomStatus
 * @property Room $Room
 * @property Crowd $Crowd
 * 
 * @method integer         getCrroCdKey()       Returns the current record's "crro_cd_key" value
 * @method integer         getCrowCdKey()       Returns the current record's "crow_cd_key" value
 * @method integer         getRoomCdKey()       Returns the current record's "room_cd_key" value
 * @method integer         getCrrsCdKey()       Returns the current record's "crrs_cd_key" value
 * @method CrowdRoomStatus getCrowdRoomStatus() Returns the current record's "CrowdRoomStatus" value
 * @method Room            getRoom()            Returns the current record's "Room" value
 * @method Crowd           getCrowd()           Returns the current record's "Crowd" value
 * @method CrowdRoom       setCrroCdKey()       Sets the current record's "crro_cd_key" value
 * @method CrowdRoom       setCrowCdKey()       Sets the current record's "crow_cd_key" value
 * @method CrowdRoom       setRoomCdKey()       Sets the current record's "room_cd_key" value
 * @method CrowdRoom       setCrrsCdKey()       Sets the current record's "crrs_cd_key" value
 * @method CrowdRoom       setCrowdRoomStatus() Sets the current record's "CrowdRoomStatus" value
 * @method CrowdRoom       setRoom()            Sets the current record's "Room" value
 * @method CrowdRoom       setCrowd()           Sets the current record's "Crowd" value
 * 
 * @package    RoomManager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCrowdRoom extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('crowd_room');
        $this->hasColumn('crro_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('crow_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('room_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('crrs_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CrowdRoomStatus', array(
             'local' => 'crrs_cd_key',
             'foreign' => 'crrs_cd_key'));

        $this->hasOne('Room', array(
             'local' => 'room_cd_key',
             'foreign' => 'room_cd_key'));

        $this->hasOne('Crowd', array(
             'local' => 'crow_cd_key',
             'foreign' => 'crow_cd_key'));
    }
}