<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Room', 'doctrine');

/**
 * BaseRoom
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $room_cd_key
 * @property integer $buil_cd_key
 * @property string $room_nm_number
 * @property integer $room_nb_vagas
 * @property Building $Building
 * @property Building $Building_2
 * @property Doctrine_Collection $RoomCrowdDatetime
 * 
 * @method integer             getRoomCdKey()         Returns the current record's "room_cd_key" value
 * @method integer             getBuilCdKey()         Returns the current record's "buil_cd_key" value
 * @method string              getRoomNmNumber()      Returns the current record's "room_nm_number" value
 * @method integer             getRoomNbVagas()       Returns the current record's "room_nb_vagas" value
 * @method Building            getBuilding()          Returns the current record's "Building" value
 * @method Building            getBuilding2()         Returns the current record's "Building_2" value
 * @method Doctrine_Collection getRoomCrowdDatetime() Returns the current record's "RoomCrowdDatetime" collection
 * @method Room                setRoomCdKey()         Sets the current record's "room_cd_key" value
 * @method Room                setBuilCdKey()         Sets the current record's "buil_cd_key" value
 * @method Room                setRoomNmNumber()      Sets the current record's "room_nm_number" value
 * @method Room                setRoomNbVagas()       Sets the current record's "room_nb_vagas" value
 * @method Room                setBuilding()          Sets the current record's "Building" value
 * @method Room                setBuilding2()         Sets the current record's "Building_2" value
 * @method Room                setRoomCrowdDatetime() Sets the current record's "RoomCrowdDatetime" collection
 * 
 * @package    RoomManager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoom extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('room');
        $this->hasColumn('room_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('buil_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('room_nm_number', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('room_nb_vagas', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Building', array(
             'local' => 'buil_cd_key',
             'foreign' => 'buil_cd_key'));

        $this->hasOne('Building as Building_2', array(
             'local' => 'buil_cd_key',
             'foreign' => 'buil_cd_key'));

        $this->hasMany('RoomCrowdDatetime', array(
             'local' => 'room_cd_key',
             'foreign' => 'room_cd_key'));
    }
}