<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RoomCrowdDatetime', 'doctrine');

/**
 * BaseRoomCrowdDatetime
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $rocd_cd_key
 * @property integer $rcds_cd_key
 * @property integer $crow_cd_key
 * @property integer $room_cd_key
 * @property integer $rocd_nb_weekday
 * @property time $rocd_dt_start_time
 * @property time $rocd_dt_final_time
 * @property RoomCrowdDatetimeStatus $RoomCrowdDatetimeStatus
 * @property Crowd $Crowd
 * @property Room $Room
 * 
 * @method integer                 getRocdCdKey()               Returns the current record's "rocd_cd_key" value
 * @method integer                 getRcdsCdKey()               Returns the current record's "rcds_cd_key" value
 * @method integer                 getCrowCdKey()               Returns the current record's "crow_cd_key" value
 * @method integer                 getRoomCdKey()               Returns the current record's "room_cd_key" value
 * @method integer                 getRocdNbWeekday()           Returns the current record's "rocd_nb_weekday" value
 * @method time                    getRocdDtStartTime()         Returns the current record's "rocd_dt_start_time" value
 * @method time                    getRocdDtFinalTime()         Returns the current record's "rocd_dt_final_time" value
 * @method RoomCrowdDatetimeStatus getRoomCrowdDatetimeStatus() Returns the current record's "RoomCrowdDatetimeStatus" value
 * @method Crowd                   getCrowd()                   Returns the current record's "Crowd" value
 * @method Room                    getRoom()                    Returns the current record's "Room" value
 * @method RoomCrowdDatetime       setRocdCdKey()               Sets the current record's "rocd_cd_key" value
 * @method RoomCrowdDatetime       setRcdsCdKey()               Sets the current record's "rcds_cd_key" value
 * @method RoomCrowdDatetime       setCrowCdKey()               Sets the current record's "crow_cd_key" value
 * @method RoomCrowdDatetime       setRoomCdKey()               Sets the current record's "room_cd_key" value
 * @method RoomCrowdDatetime       setRocdNbWeekday()           Sets the current record's "rocd_nb_weekday" value
 * @method RoomCrowdDatetime       setRocdDtStartTime()         Sets the current record's "rocd_dt_start_time" value
 * @method RoomCrowdDatetime       setRocdDtFinalTime()         Sets the current record's "rocd_dt_final_time" value
 * @method RoomCrowdDatetime       setRoomCrowdDatetimeStatus() Sets the current record's "RoomCrowdDatetimeStatus" value
 * @method RoomCrowdDatetime       setCrowd()                   Sets the current record's "Crowd" value
 * @method RoomCrowdDatetime       setRoom()                    Sets the current record's "Room" value
 * 
 * @package    RoomManager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoomCrowdDatetime extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('room_crowd_datetime');
        $this->hasColumn('rocd_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('rcds_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('crow_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('room_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('rocd_nb_weekday', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('rocd_dt_start_time', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('rocd_dt_final_time', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RoomCrowdDatetimeStatus', array(
             'local' => 'rcds_cd_key',
             'foreign' => 'rcds_cd_key'));

        $this->hasOne('Crowd', array(
             'local' => 'crow_cd_key',
             'foreign' => 'crow_cd_key'));

        $this->hasOne('Room', array(
             'local' => 'room_cd_key',
             'foreign' => 'room_cd_key'));
    }
}