<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Subject', 'doctrine');

/**
 * BaseSubject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $subj_cd_key
 * @property string $subj_nm_code
 * @property string $subj_nm_name
 * @property integer $cour_cd_key
 * @property Course $Course
 * @property Doctrine_Collection $Crowd
 * 
 * @method integer             getSubjCdKey()    Returns the current record's "subj_cd_key" value
 * @method string              getSubjNmCode()   Returns the current record's "subj_nm_code" value
 * @method string              getSubjNmName()   Returns the current record's "subj_nm_name" value
 * @method integer             getCourCdKey()    Returns the current record's "cour_cd_key" value
 * @method Course              getCourse()       Returns the current record's "Course" value
 * @method Doctrine_Collection getCrowd()        Returns the current record's "Crowd" collection
 * @method Subject             setSubjCdKey()    Sets the current record's "subj_cd_key" value
 * @method Subject             setSubjNmCode()   Sets the current record's "subj_nm_code" value
 * @method Subject             setSubjNmName()   Sets the current record's "subj_nm_name" value
 * @method Subject             setCourCdKey()    Sets the current record's "cour_cd_key" value
 * @method Subject             setCourse()       Sets the current record's "Course" value
 * @method Subject             setCrowd()        Sets the current record's "Crowd" collection
 * 
 * @package    RoomManager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subject');
        $this->hasColumn('subj_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('subj_nm_code', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('subj_nm_name', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 40,
             ));
        $this->hasColumn('cour_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Course', array(
             'local' => 'cour_cd_key',
             'foreign' => 'cour_cd_key'));

        $this->hasMany('Crowd', array(
             'local' => 'subj_cd_key',
             'foreign' => 'subj_cd_key'));
    }
}