<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Timetable', 'doctrine');

/**
 * BaseTimetable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $time_cd_key
 * @property date $time_dt_time
 * @property Doctrine_Collection $Crowd
 * 
 * @method integer             getTimeCdKey()    Returns the current record's "time_cd_key" value
 * @method date                getTimeDtTime()   Returns the current record's "time_dt_time" value
 * @method Doctrine_Collection getCrowd()        Returns the current record's "Crowd" collection
 * @method Timetable           setTimeCdKey()    Sets the current record's "time_cd_key" value
 * @method Timetable           setTimeDtTime()   Sets the current record's "time_dt_time" value
 * @method Timetable           setCrowd()        Sets the current record's "Crowd" collection
 * 
 * @package    RoomManager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTimetable extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('timetable');
        $this->hasColumn('time_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('time_dt_time', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Crowd', array(
             'local' => 'time_cd_key',
             'foreign' => 'time_cd_key'));
    }
}