<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Course', 'doctrine');

/**
 * BaseCourse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $cour_cd_key
 * @property integer $cour_nb_code
 * @property string $cour_nm_name
 * @property Doctrine_Collection $Subject
 * 
 * @method integer             getCourCdKey()    Returns the current record's "cour_cd_key" value
 * @method integer             getCourNbCode()   Returns the current record's "cour_nb_code" value
 * @method string              getCourNmName()   Returns the current record's "cour_nm_name" value
 * @method Doctrine_Collection getSubject()      Returns the current record's "Subject" collection
 * @method Course              setCourCdKey()    Sets the current record's "cour_cd_key" value
 * @method Course              setCourNbCode()   Sets the current record's "cour_nb_code" value
 * @method Course              setCourNmName()   Sets the current record's "cour_nm_name" value
 * @method Course              setSubject()      Sets the current record's "Subject" collection
 * 
 * @package    RoomManager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCourse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('course');
        $this->hasColumn('cour_cd_key', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cour_nb_code', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cour_nm_name', 'string', 80, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 80,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Subject', array(
             'local' => 'cour_cd_key',
             'foreign' => 'cour_cd_key'));
    }
}