<?php

/**
 * RoomCrowdDatetime
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    RoomManager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class RoomCrowdDatetime extends BaseRoomCrowdDatetime
{

    public function getWeekday(){
        switch ($this->getRocdNbWeekday())
        {
            case 1:
                return "Segunda";
                break;
            case 2:
                return "Terça";
                break;
            case 3:
                return "Quarta";
                break;
            case 4:
                return "Quinta";
                break;
            case 5:
                return "Sexta";
                break;
            default :
                return "Sabado";

        }
    }

    public function getDetailedInformation()
    {
        return $this->getRocdDtStartTime()."/".$this->getRocdDtFinalTime()." ". ($this->getRoomCdKey() ? $this->getRoom() : "");
    }

    public function getTimetable()
    {
        return $this->getRocdDtStartTime()."/".$this->getRocdDtFinalTime();
    }

    public function getRocdDtStartTime()
    {
        $time = $this->_get('rocd_dt_start_time');
        $time = explode(':', $time);
        return date('H:i', mktime($time[0], $time[1], $time[2]));
    }

    public function getRocdDtFinalTime()
    {
        $time = $this->_get('rocd_dt_final_time');
        $time = explode(':', $time);
        return date('H:i', mktime($time[0], $time[1], $time[2]));
    }
}