<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/11/20 16:26:42

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=127.0.0.1;dbname=room_manager',
  'username' => 'root',
  'password' => '123456',
  'name' => 'doctrine',
)),);
