<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/11/20 16:26:57
sfConfig::add(array(
  'mod_roomcrowddatetime_enabled' => true,
  'mod_roomcrowddatetime_view_class' => 'sfPHP',
));
